// <auto-generated />
using System;
using FundDca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FundDca.Data.Migrations
{
    [DbContext(typeof(FundDcaDbContext))]
    [Migration("20260911060507_M3_Buy_Trades")]
    partial class M3_Buy_Trades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FundDca.Core.Domain.BudgetMonth", b =>
                {
                    b.Property<string>("YearMonth")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("year_month");

                    b.Property<bool>("BondSweepDone")
                        .HasColumnType("boolean")
                        .HasColumnName("bond_sweep_done");

                    b.Property<decimal>("BudgetAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("budget_amount");

                    b.Property<decimal>("InvestedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("invested_amount");

                    b.HasKey("YearMonth");

                    b.ToTable("budget_months", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.DailySnapshot", b =>
                {
                    b.Property<string>("FundCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fund_code");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DayChangePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("day_change_percent");

                    b.Property<decimal>("MarketValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("market_value");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shares");

                    b.Property<decimal>("UnitNav")
                        .HasPrecision(12, 5)
                        .HasColumnType("numeric(12,5)")
                        .HasColumnName("unit_nav");

                    b.HasKey("FundCode", "TradeDate");

                    b.HasIndex("TradeDate");

                    b.ToTable("daily_snapshots", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.DcaSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FixedInvestAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fixed_invest_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("dca_settings", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.Fund", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<decimal?>("BuyFeeRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("buy_fee_rate");

                    b.Property<string>("DividendMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("REINVEST")
                        .HasColumnName("dividend_method");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("RedeemFeeTiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("redeem_fee_tiers");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<string>("TrackedIndexCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tracked_index_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type");

                    b.Property<bool>("UseManualValue")
                        .HasColumnType("boolean")
                        .HasColumnName("use_manual_value");

                    b.HasKey("Code");

                    b.HasIndex("SectorId");

                    b.HasIndex("TrackedIndexCode");

                    b.ToTable("funds", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.FundNav", b =>
                {
                    b.Property<string>("FundCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fund_code");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<decimal?>("AccNav")
                        .HasPrecision(12, 5)
                        .HasColumnType("numeric(12,5)")
                        .HasColumnName("acc_nav");

                    b.Property<decimal?>("DayChangePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("day_change_percent");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<decimal>("UnitNav")
                        .HasPrecision(12, 5)
                        .HasColumnType("numeric(12,5)")
                        .HasColumnName("unit_nav");

                    b.HasKey("FundCode", "TradeDate");

                    b.HasIndex("FundCode");

                    b.ToTable("fund_navs", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.FundOverlap", b =>
                {
                    b.Property<int>("OverlapGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("overlap_group_id");

                    b.Property<string>("FundCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fund_code");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("OverlapGroupId", "FundCode");

                    b.HasIndex("FundCode");

                    b.ToTable("fund_overlaps", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.Holding", b =>
                {
                    b.Property<string>("FundCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fund_code");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_amount");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shares");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FundCode");

                    b.ToTable("holdings", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.IndexInfo", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<decimal>("HighThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("high_threshold_percent");

                    b.Property<decimal>("LowThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("low_threshold_percent");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("metric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("ProxyCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proxy_code");

                    b.Property<int>("WindowYears")
                        .HasColumnType("integer")
                        .HasColumnName("window_years");

                    b.HasKey("Code");

                    b.ToTable("indexes", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.IndexValuation", b =>
                {
                    b.Property<string>("IndexCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("index_code");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<decimal?>("Pb")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("pb");

                    b.Property<decimal?>("PbPercentile")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("pb_percentile");

                    b.Property<decimal?>("PePercentile")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("pe_percentile");

                    b.Property<decimal?>("PeTtm")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("pe_ttm");

                    b.Property<string>("ResolvedCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resolved_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("IndexCode", "TradeDate");

                    b.HasIndex("TradeDate");

                    b.ToTable("index_valuations", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.ManualValue", b =>
                {
                    b.Property<string>("FundCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fund_code");

                    b.Property<decimal>("MarketValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("market_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("FundCode");

                    b.ToTable("manual_values", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.OverlapGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("overlap_groups", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEquity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_equity");

                    b.Property<decimal>("LimitPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("limit_percent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<decimal?>("ConfirmedNav")
                        .HasPrecision(12, 5)
                        .HasColumnType("numeric(12,5)")
                        .HasColumnName("confirmed_nav");

                    b.Property<decimal?>("ConfirmedShares")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("confirmed_shares");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedShares")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("estimated_shares");

                    b.Property<string>("FundCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fund_code");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.HasKey("Id");

                    b.HasIndex("FundCode");

                    b.HasIndex("Status", "TradeDate");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.DailySnapshot", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundDca.Core.Domain.Fund", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FundDca.Core.Domain.IndexInfo", "TrackedIndex")
                        .WithMany()
                        .HasForeignKey("TrackedIndexCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");

                    b.Navigation("TrackedIndex");
                });

            modelBuilder.Entity("FundDca.Core.Domain.FundNav", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundDca.Core.Domain.FundOverlap", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundDca.Core.Domain.OverlapGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("OverlapGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FundDca.Core.Domain.Holding", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Fund", "Fund")
                        .WithOne()
                        .HasForeignKey("FundDca.Core.Domain.Holding", "FundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundDca.Core.Domain.IndexValuation", b =>
                {
                    b.HasOne("FundDca.Core.Domain.IndexInfo", "Index")
                        .WithMany()
                        .HasForeignKey("IndexCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Index");
                });

            modelBuilder.Entity("FundDca.Core.Domain.ManualValue", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Fund", "Fund")
                        .WithOne()
                        .HasForeignKey("FundDca.Core.Domain.ManualValue", "FundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundDca.Core.Domain.Trade", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundDca.Core.Domain.OverlapGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
