// <auto-generated />
using FundDca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FundDca.Data.Migrations
{
    [DbContext(typeof(FundDcaDbContext))]
    [Migration("20260911014057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FundDca.Core.Domain.Fund", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<decimal?>("BuyFeeRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("buy_fee_rate");

                    b.Property<string>("DividendMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("REINVEST")
                        .HasColumnName("dividend_method");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("RedeemFeeTiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("redeem_fee_tiers");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<string>("TrackedIndexCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tracked_index_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type");

                    b.HasKey("Code");

                    b.HasIndex("SectorId");

                    b.HasIndex("TrackedIndexCode");

                    b.ToTable("funds", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.FundOverlap", b =>
                {
                    b.Property<int>("OverlapGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("overlap_group_id");

                    b.Property<string>("FundCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fund_code");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("OverlapGroupId", "FundCode");

                    b.HasIndex("FundCode");

                    b.ToTable("fund_overlaps", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.IndexInfo", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<decimal>("HighThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("high_threshold_percent");

                    b.Property<decimal>("LowThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("low_threshold_percent");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("metric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("WindowYears")
                        .HasColumnType("integer")
                        .HasColumnName("window_years");

                    b.HasKey("Code");

                    b.ToTable("indexes", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.OverlapGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("overlap_groups", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEquity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_equity");

                    b.Property<decimal>("LimitPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("limit_percent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("FundDca.Core.Domain.Fund", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FundDca.Core.Domain.IndexInfo", "TrackedIndex")
                        .WithMany()
                        .HasForeignKey("TrackedIndexCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");

                    b.Navigation("TrackedIndex");
                });

            modelBuilder.Entity("FundDca.Core.Domain.FundOverlap", b =>
                {
                    b.HasOne("FundDca.Core.Domain.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundDca.Core.Domain.OverlapGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("OverlapGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FundDca.Core.Domain.OverlapGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
